management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8200
  
spring:
  datasource:
    url: jdbc:postgresql://${STOCKKEEPER_DB}:5432/stockkeeper
    username: stockkeeper
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
